import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/header';
import GoogleAnalytics from '@/components/analytics/google-analytics';
import CookieBanner from '@/components/analytics/cookie-banner';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<GoogleAnalytics GA_MEASUREMENT_ID="G-9LRGBMQP2V" />
			<body className={inter.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
				>
					{/* <Header /> */}
					{children}
					<CookieBanner />
					{/* <Footer /> */}
				</ThemeProvider>
			</body>
		</html>
	);
}
